services:

  vr:
    image: nginx:alpine
    container_name: szurubooru-vr
    ports:
      - "8081:80" # change if needed
    volumes:
      - ./vrviewer:/usr/share/nginx/html:ro
      - ./vrviewer/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    # networks: # Change or add additional networks
      # - proxy
      
# Additional networks such as proxy
# networks:
    # proxy:
      # external: true
